SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE HOMETV.SETTING;
TRUNCATE TABLE HOMETV.PLAY_LIST_ITEM;
TRUNCATE TABLE HOMETV.CHANNEL;
TRUNCATE TABLE HOMETV.RENDERER;
SET REFERENTIAL_INTEGRITY TRUE;