#!/bin/bash
# /etc/init.d/hometv-master-server

### BEGIN INIT INFO
# Provides:          hometv-master-server
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: HomeTV Master
# Description: 
### END INIT INFO

export JAVA_HOME=/usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt

BASE_DIR=/usr/share/hometv-master-server
PID_FILE=/var/run/hometv-master-server.pid
CLASSPATH="lib/*"
MAIN_CLASS=ch.wellernet.hometv.master.impl.Main

case "$1" in 
    start)
        echo "Starting HomeTV Master"
        cd $BASE_DIR
        jsvc -home $JAVA_HOME -pidfile $PID_FILE -server -cp "$CLASSPATH" $MAIN_CLASS
        ;;
    stop)
        echo "Stopping HomeTV Master"
        cd $BASE_DIR
        jsvc -stop -home $JAVA_HOME -pidfile $PID_FILE -server -cp "$CLASSPATH" $MAIN_CLASS
        ;;
    *)
        echo "Usage: /etc/init.d/hometv-master-server start|stop"
        exit 1
        ;;
esac

exit 0